language: python
python:
  — 3.9
  — 2.7
install:
# Install Python dependencies using pipenv and install the package itself in editable mode for testing purposes
  — pip install -r requirements-dev.txt
script:
  — flake8
    
 

