# Generated by Django 4.2.3 on 2023-07-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosEleitorais',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('titulo_eleitor', models.CharField(max_length=12)),
                ('zona_eleitoral', models.IntegerField()),
                ('secao_eleitoral', models.IntegerField()),
            ],
        ),
    ]
